from __future__ import annotations

# Static router exclusions for non-deprecated models returned by
# ``ChatNVIDIA.get_available_models()``. This includes undersized models and
# models observed repeatedly violating required native tool-call contracts.
BANNED_MODEL_IDS_UNDER_30B: tuple[str, ...] = (
    "bytedance/seed-oss-36b-instruct",
    "google/codegemma-7b",
    "google/gemma-2-2b-it",
    "google/gemma-3-12b-it",
    "google/gemma-3-27b-it",
    "google/gemma-3-4b-it",
    "google/gemma-3n-e2b-it",
    "google/gemma-3n-e4b-it",
    "google/gemma-4-31b-it",
    "google/paligemma",
    "meta/llama-3.1-8b-instruct",
    "meta/llama-3.1-70b-instruct",
    "meta/llama-3.2-11b-vision-instruct",
    "meta/llama-3.2-1b-instruct",
    "meta/llama-3.2-3b-instruct",
    "meta/llama-guard-4-12b",
    "microsoft/phi-3-vision-128k-instruct",
    "microsoft/phi-4-mini-instruct",
    "microsoft/phi-4-multimodal-instruct",
    "moonshotai/kimi-k2-instruct-0905",
    "mistralai/codestral-22b-instruct-v0.1",
    "mistralai/mathstral-7b-v0.1",
    "mistralai/ministral-14b-instruct-2512",
    "mistralai/ministral-3-14b-instruct-2512",
    "mistralai/mistral-7b-instruct-v0.3",
    "mistralai/mistral-nemotron",
    "nvidia/llama-3.1-nemoguard-8b-content-safety",
    "nvidia/llama-3.1-nemoguard-8b-topic-control",
    "nvidia/llama-3.1-nemotron-nano-8b-v1",
    "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
    "nvidia/nemoretriever-parse",
    "nvidia/nemotron-mini-4b-instruct",
    "nvidia/nemotron-nano-12b-v2-vl",
    "nvidia/nvclip",
    "nvidia/nvidia-nemotron-nano-9b-v2",
    "nvidia/nemotron-3-ultra-550b-a55b",
    "openai/gpt-oss-20b",
    "stepfun-ai/step-3.5-flash",
    "stepfun-ai/step-3.7-flash",
    "nvidia/nemotron-3-nano-30b-a3b",
    "qwen/qwen3.5-122b-a10b",
    "upstage/solar-10.7b-instruct",
    "zyphra/zamba2-7b-instruct",
    "z-ai/glm-5.1",
)
